<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Snap.Hutao.Remastered\Service\SupportedCultures.cs" Link="Service\SupportedCultures.cs" />
    <Compile Include="..\Snap.Hutao.Remastered\Service\CultureOptions.CurrentCulture.cs" Link="Service\CultureOptions.CurrentCulture.cs" />
    <Compile Include="..\Snap.Hutao.Remastered\Core\Setting\SettingKeys.cs" Link="Core\Setting\SettingKeys.cs" />
    <Compile Include="..\Snap.Hutao.Remastered\Core\Property\IObservableProperty.cs" Link="Core\Property\IObservableProperty.cs" />
    <Compile Include="..\Snap.Hutao.Remastered\Core\Property\IProperty.cs" Link="Core\Property\IProperty.cs" />
    <Compile Include="..\Snap.Hutao.Remastered\Core\Property\INotifyPropertyChangedDeferral.cs" Link="Core\Property\INotifyPropertyChangedDeferral.cs" />
    <Compile Include="..\Snap.Hutao.Remastered\Model\NameValue.cs" Link="Model\NameValue.cs" />
    <Compile Include="..\Snap.Hutao.Remastered\Model\NameCultureInfoValue.cs" Link="Model\NameCultureInfoValue.cs" />
    <Compile Include="..\Snap.Hutao.Remastered\Model\LocalizationSource.cs" Link="Model\LocalizationSource.cs" />
    <Using Include="System" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.ComponentModel" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.4.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.4.0" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Threading.RateLimiting" Version="10.0.12" />
  </ItemGroup>

</Project>
